version: "3"
services:
  mongo:
    container_name: mongo-container
    image: mongo:4
    restart: always
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
  api:
    container_name: api-container
    build: .
    image: dorper-moda-api
    restart: always
    command: bash -c "npm install && npm start"
    environment:
      - MONGO_URL=mongodb://mongo:27017/dorper-moda-api
    volumes:
      - ./dist/:/usr/src/dorper-moda-api/dist/
      - ./package.json:/usr/src/dorper-moda-api/package.json
    ports:
      - "5000:5000"
    links:
      - mongo
